### ISSUE TITLE
Running inside tmux

### ISSUE THREAD

**Issue by anufrievroman** [EdinCitaku/TerminalMuseum#2]
Hello, nice app. Typically, I use tmux, but it does not seem to run well with terminalmuseum. Outside tmux it work fine, but inside tmux it says 'Checking for graphics (10.0s max. wait)...' and after 10 seconds 'This terminal emulator does not support the graphics protocol, use a terminal emulator such as kitty that does support it'. I am using kitty. Thank you.

**Comment by kovidgoyal** [comment]
tmux does not support graphics.

**Comment by anufrievroman** [comment]
Even so, is it possible then that the app does not start if it is inside tmux? I mean, imagine you actually put into your bashrc and now you can't use tmux because it freezes for 10 seconds. Perhaps this graphics check time can be reduced somehow.

**Comment by EdinCitaku** [comment]
You could check in ur bashrc if you are in a tmux session. And run terminalmuseum only if ur not in tmux.
See:
https://unix.stackexchange.com/questions/10689/how-can-i-tell-if-im-in-a-tmux-session-from-a-bash-script

So the bashrc would look smth like
```bash
if  [ "$TERM_PROGRAM" != tmux ]; then                                                                                                                                         
  terminalmuseum --command "kitty +kitten icat" --print_title                                                                                                                 
fi
```
if you are in tmux u could use imgcat instead

**Comment by anufrievroman** [comment]
Okay, thank you, let's consider it resolved.
